name: lighthouse

on:
  pull_request:
    branches: [master]

jobs:
  lhci:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7

      - name: Wait for Vercel preview
        id: vercel
        uses: patrickedqvist/wait-for-vercel-preview@v1.3.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 600

      - name: Lighthouse CI
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            ${{ steps.vercel.outputs.url }}/
            ${{ steps.vercel.outputs.url }}/download
            ${{ steps.vercel.outputs.url }}/docs/getting-started
            ${{ steps.vercel.outputs.url }}/privacy
          uploadArtifacts: true
          temporaryPublicStorage: true
          configPath: "./.github/lighthouserc.json"
